config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  get '/about', to: 'page#about'
  get '/guides', to: 'page#guides'

  resources :institutions do
    resources :reviews, except: [:index]
  end
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :reviews, dependent: :destroy


  validates :name,
            presence: true

  validates :address,
            presence: true

  validates :telephone,
            length: { minimum: 8, maximum: 15 },
            format: {
              with: /\A[ \+\(\)\d]+\z/,
              message: 'Must be a phone number'
            }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :institution


  validates :rating,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than_or_equal_to:    5
            }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  def create
    @institution = Institution.new(institution_params)

    if @institution.save
      redirect_to @institution, notice: 'Institution was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /institutions/1
  def update
    if @institution.update(institution_params)
      redirect_to @institution, notice: 'Institution was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /institutions/1
  # def destroy
  #   @institution.destroy
  #   redirect_to institutions_url, notice: 'Institution was successfully destroyed.'
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def institution_params
      params.require(:institution).permit(:name, :address, :telephone, :link)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    render layout: false
  end

  def about
    render 'About.html'
  end

  def guides
    render 'Guides.html'
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_institution
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews/1
  def show
  end

  # GET /reviews/new
  def new
    @institution = Institution.find(params[:institution_id])
    @review = Review.new(institution: @institution)
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to institution_review_path(@institution, @review),
                  notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /reviews/1
  def update
    if @review.update(review_params)
      redirect_to @review, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reviews/1
  # def destroy
  #   @review.destroy
  #   redirect_to reviews_url, notice: 'Review was successfully destroyed.'
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  def set_institution
    @institution = Institution.find(params[:institution_id])
  end

  # Only allow a trusted parameter "white list" through.
  def review_params
    args = params.require(:review).permit(
      :rating, :youth_friendly, :title, :body
    )
    args[:institution_id] = params.require(:institution_id)
    args
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/institutions/_form.html.erb
<%= form_for(@institution) do |f| %>
  <% if @institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% @institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Telephone</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= link_to institution.name, institution %></td>
        <td><%= institution.telephone %></td>
        <td><%= link_to 'Homepage', institution.link %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <%# <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %1></td> %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @institution.address %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @institution.telephone %>
</p>

<p>
  <%= link_to 'Homepage', @institution.link %>
</p>

<p>
  <%= link_to 'New Review', new_institution_review_path(@institution) %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Youth friendly</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institution.reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.youth_friendly %></td>
        <td><%= review.title %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', institution_review_path(@institution, review) %></td>
        <td><%= link_to 'Edit', edit_institution_review_path(@institution, review) %></td>
        <%# <td><%= link_to 'Destroy', [@institution, review], method: :delete, data: { confirm: 'Are you sure?' } %1></td> %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transadvisor</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= link_to '/' do %>
    <center><img height=200 src="<%= image_url("Small_TransAdvisor_Logo.png") %>" alt="TransAdvisor Logo" align="center" ></center>
  <% end %>
    <div class="nav">
      <div class="container">
        <ul class="nav-menu">
          <li><a href="/about"> About </a></li>
          <li><a href="/guides">Guides</a></li>
          <li><%= link_to 'Institutions', institutions_path %></li>
        </ul>
        <%# <ul> %>
        <%#   <li><a href="#">Write Review</a></li> %>
        <%#   <li><a href="#">Read Review</a></li> %>
        <%#   <li><a href="#">Log In</a></li> %>
        <%# </ul> %>
      </div>
    </div>
<%= yield %>
<div class="learn-more">
	  <div>
		<div>
	  	  <div>
			<h3>About</h3>
			<p>TransAdvisor was created for trans people by a...</p>
			<p><a href="#">Click here to learn more.</a></p>
		  </div>
		  <div>
			<h3>Guide</h3>
			<p>This is our guid of things to think about...</p>
			<p><a href="#">Click here to read our guides.</a></p>
		  </div>
		  <div>
			<h3>Reviews</h3>
			<p>Leave your reviews and read reviews left by...</p>
			<p><a href="#">Click here for reviews.</a></p>
		  </div>
	    </div>
	  </div>
	</div>
</body>
</html>

app/views/page/About.html.erb
<!DOCTYPE html>
<html>
  <head>
      <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/shift.css" rel="stylesheet">
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
      <link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
</head>

<body>

  <h1>About</h1>
  <div>
  <div>
<p>TransAdvisor was created for trans people by a collaboration of trans people and trans allies who have an interest in building software solutions to make trans people’s lives easier. It came into being at Trans*Code, in March 2015. </p>


<p>TransAdvisor is designed to help people who fall under the trans umbrella make choices about the healthcare providers they access by providing reviews of how trans-friendly a healthcare provider or institution is, according to trans people who have accessed that service. Trans people can then find out how trans-friendly their local health services are before they visit, and potentially switch healthcare providers based on reviews of both individuals and institutions.</p>
</div>
</div>
</body>

</html>

app/views/page/Guides.html.erb
<!DOCTYPE html>
<html>
  <head>
      <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/shift.css" rel="stylesheet">
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
      <link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
</head>

<body>

  <h1>Guides</h1>
  <div>
  <div>
<h2>Things to think about when writing your review of Individual:</h2>
<p>When you are writing a about a person try to be respectful, however some people are more respectful than others so it is understandable if you just want to advise people to stay away.  Good things to include would be how did they treat you, how they referred to you, and what sort of action they took/advised.</p>


<h2>Things to think about when writing your review of the Institution:</h2>
<p>When you are writing about an Institution, if the experience was less than ideal, try and think about what you would have wanted.  Good things to include would be where the reception staff respectful ? Did they make the effort to listen to you & understand. Did they call out (correct) names & pronouns in the waiting room or was it anonymised eg with ticket numbers? How was the accessibility of the location? Were you asked questions which seemed irrelevant to your visit & were inappropriate or overly personal ?</p>

<p>You may not want to talk about general problems such as long waiting times or location that are already covered by more general reviews medical reports.</p>

<h2>What the words mean:</h2>
<h3>Health Institution</h3>
<p>This is any location that administers health care or health advice that you would want to know more information about before visiting or deciding if you should visit.</p>

<h3>Health care professional</h3>
<p>These are any of the people that you may come across during your interactions with -ealth services, examples would include by are not limited to:
<li>GP</li>
<li>Surgeon</li>
<li>Consultant</li>
<li>Psychotherapist</li>
<li>Psychiatrists</li>
<li>Speech therapist</li>

<h3>Trans</h3>
<p>Anyone who identifies as trans or falling under the trans umbrella, including men and women who identity differently to the gender they were assigned at birth, genderqueer, genderfluid and gender-neutral/non-binary people, intersex people and anyone else who does not identify as cisgender.</p>

<p>Cisgender = individuals who identify with the gender they were assigned at birth. If you identify as cisgender, please recommend this website to your trans friends. </p>

These gender definitions are not perfect, exhaustive or set in stone.

<h2>Advice about accessing health care</h2>
<p>Information to people about how to access healthcare and what to expect.</p>

<p>Accessing health care if your gender identity or presentation does not align with what your doctor might expect can be anything from needlessly uncomfortable to downright impossible. </p>

<p>Doctors and other healthcare providers will not necessarily have training specifically for or know protocols gender identity issues.  Before approaching a doctor to access such services it is advisable to be clear about what you want to happen, what you want your doctor to do for you and to know what the protocols are for accessing the services that you want as you will probably need to explain the protocols to your GP.</p>

<p>A good starting point to find about accessing NHS services is here:-</p>
<a href="http://www.nhs.uk/Livewell/Transhealth/Pages/Transhealthhome.aspx">http://www.nhs.uk/Livewell/Transhealth/Pages/Transhealthhome.aspx</a><br>


<p>Other helpful resources related to accessing healthcare as a transperson:</p>
<a href="http://www.nhs.uk/Livewell/Transhealth/Pages/Transhealthhome.aspx">http://www.nhs.uk/Livewell/Transhealth/Pages/Transhealthhome.aspx</a><br>
<a href="http://genderedintelligence.co.uk/trans-community/resources">http://genderedintelligence.co.uk/trans-community/resources</a><br>
<a href= "http://genderedintelligence.co.uk/trans-community/resources">http://genderedintelligence.co.uk/trans-community/resources</a><br>
<a href= "http://cliniq.org.uk/">http://cliniq.org.uk/</a></p>

</div>
</div>
</body>

</html>

app/views/page/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/shift.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
  </head>


  <body>
  <%= link_to '/' do %>
    <center><img src="<%= image_url("TransAdvisor_Logo.png") %>" alt="TransAdvisor Logo" align="center" height="300" width="300"></center>
  <% end %>
    <div class="nav">
      <div class="container">
        <ul>
          <li><a href="/about"> About </a></li>
          <li><a href="/guides">Guides</a></li>
          <li><%= link_to 'Institutions', institutions_path %></li>
        </ul>
        <%# <ul> %>
        <%#   <li><a href="#">Write Review</a></li> %>
        <%#   <li><a href="#">Read Review</a></li> %>
        <%#   <li><a href="#">Log In</a></li> %>
        <%# </ul> %>
      </div>
    </div>

    <div class="jumbotron">
      <div class="container">
        <h1>Leave A Review Today.</h1>
        <p>Reviews of health services for trans people</p>
      </div>
    </div>

    <div class="learn-more">
	  <div>
		<div>
	  	  <div>
          <p>Welcome to TransAdvisor - the website for trans people to review their healthcare and search for trans-friendly healthcare providers. GPs, sexual health services, mental health services and other healthcare providers can make accessing health care easier or harder depending on their attitude towards and knowledge and experience of trans issues. Accessing health care can be intimidating if you don’t know how your gender presentation or identity will be received by your caregiver - TransAdvisor aims to help trans people access friendly and inclusive healthcare and alert other trans people to healthcare providers and institutions that might make them feel unwelcome and unsafe.</p>
			<h3>About</h3>
			<p>TransAdvisor was created for trans people by a...</p>
			<p><a href="#">Click here to learn more.</a></p>
		  </div>
		  <div>
			<h3>Guide</h3>
			<p>This is our guid of things to think about...</p>
			<p><a href="#">Click here to read our guides.</a></p>
		  </div>
		  <div>
			<h3>Reviews</h3>
			<p>Leave your reviews and read reviews left by...</p>
			<p><a href="#">Click here for reviews.</a></p>
		  </div>
	    </div>
	  </div>
	</div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@institution, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.select :rating, [nil] + ((0..5).map {|i| [i,i] }) %>
  </div>
  <div class="field">
    <%= f.label :youth_friendly %><br>
    <%= f.check_box :youth_friendly %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Youth friendly</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.youth_friendly %></td>
        <td><%= review.title %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', institution_review_path(@institution, review) %></td>
        <td><%= link_to 'Edit', edit_institution_review_path(@institution, review) %></td>
        <td><%= link_to 'Destroy', [@institution, review], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_institution_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path(@institution) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Youth friendly:</strong>
  <%= @review.youth_friendly %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<%= link_to 'Edit', edit_institution_review_path(@institution, @review) %>
<%= link_to 'Back', institution_path(@institution) %>